version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redmine-api-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: >
      bash -c "chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache &&
               chmod -R 775 /var/www/storage /var/www/bootstrap/cache &&
               php-fpm"
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - redmine-api-network

  db:
    image: mysql:8.0
    container_name: redmine-api-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3309:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - redmine-api-network

  nginx:
    image: nginx:alpine
    container_name: redmine-api-nginx
    restart: unless-stopped
    ports:
      - "8083:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - redmine-api-network

networks:
  redmine-api-network:
    driver: bridge

volumes:
  dbdata: 